const BUTTON = {
  BUTTON: "BUTTON",
  PRIMARY: "PRIMARY",
  OUTLINE: "OUTLINE",
  LINK: "LINK",
};

const FROM = {
  PLAYLIST: "PLAYLIST",
  HOME: "HOME",
  HISTORY: "HISTORY",
  LIKES: "LIKES",
};

export { BUTTON, FROM };
